##
## Don't pay attention
## Sometime I am tired to return on the root dir and I launch the compilation from this dir
## The real MAKEFILE is still the one at the root of the dir

all:
	make -s -C ../

clean:
	make clean -s -C ../

fclean:	clean
	make fclean -s -C ../

re:	fclean all
